---
resources:
- name: booklit
  type: git
  source:
    uri: https://github.com/concourse/booklit
    branch: master

jobs:
- name: unit
  plan:
  - get: booklit
    trigger: true
  - task: unit
    file: booklit/ci/test.yml