# vault-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          command: ["vault", "server", "-dev"]
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
            - name: vault-storage
              mountPath: /vault/data
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
        - name: vault-storage
          persistentVolumeClaim:
            claimName: vault-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  type: NodePort
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: 30200
  selector:
    app: vault
